/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerInput = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Category = IDL.Variant({
  'Syrup' : IDL.Null,
  'Drops' : IDL.Null,
  'Capsule' : IDL.Null,
  'Injection' : IDL.Null,
  'Tablet' : IDL.Null,
  'Other' : IDL.Null,
  'Cream' : IDL.Null,
});
export const MedicineInput = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'discount' : IDL.Float64,
  'category' : Category,
  'brand' : IDL.Text,
  'price' : IDL.Float64,
});
export const SupplierInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gstNo' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const BillItemInput = IDL.Record({
  'hsnSac' : IDL.Opt(IDL.Text),
  'discount' : IDL.Float64,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'medicineId' : IDL.Nat,
  'amount' : IDL.Float64,
  'medicineName' : IDL.Text,
});
export const BillInput = IDL.Record({
  'customerGstin' : IDL.Opt(IDL.Text),
  'gstPercent' : IDL.Float64,
  'receivedAmount' : IDL.Opt(IDL.Float64),
  'paymentMode' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Nat,
  'placeOfSupply' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(BillItemInput),
});
export const SupplierBillItem = IDL.Record({
  'sn' : IDL.Nat,
  'hsn' : IDL.Text,
  'mfg' : IDL.Text,
  'mrp' : IDL.Float64,
  'qty' : IDL.Nat,
  'free' : IDL.Nat,
  'pack' : IDL.Text,
  'rate' : IDL.Float64,
  'gstPercent' : IDL.Float64,
  'discPercent' : IDL.Float64,
  'netAmt' : IDL.Float64,
  'expDt' : IDL.Text,
  'itemName' : IDL.Text,
  'batchNo' : IDL.Text,
  'amount' : IDL.Float64,
});
export const SupplierBillInput = IDL.Record({
  'salesMan' : IDL.Opt(IDL.Text),
  'addLessCnDn' : IDL.Float64,
  'challanNo' : IDL.Opt(IDL.Text),
  'date' : IDL.Int,
  'lrNo' : IDL.Opt(IDL.Text),
  'transport' : IDL.Opt(IDL.Text),
  'invoiceNo' : IDL.Text,
  'cashDiscountTotal' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'freightPktCharge' : IDL.Float64,
  'schemeDiscountTotal' : IDL.Float64,
  'items' : IDL.Vec(SupplierBillItem),
  'cgstAmount' : IDL.Float64,
  'sgstAmount' : IDL.Float64,
  'roundOff' : IDL.Float64,
  'supplierId' : IDL.Nat,
  'termsConditions' : IDL.Opt(IDL.Text),
});
export const SupplierBill = IDL.Record({
  'id' : IDL.Nat,
  'salesMan' : IDL.Opt(IDL.Text),
  'addLessCnDn' : IDL.Float64,
  'challanNo' : IDL.Opt(IDL.Text),
  'supplierName' : IDL.Text,
  'date' : IDL.Int,
  'lrNo' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'transport' : IDL.Opt(IDL.Text),
  'invoiceNo' : IDL.Text,
  'cashDiscountTotal' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'freightPktCharge' : IDL.Float64,
  'schemeDiscountTotal' : IDL.Float64,
  'items' : IDL.Vec(SupplierBillItem),
  'cgstAmount' : IDL.Float64,
  'sgstAmount' : IDL.Float64,
  'roundOff' : IDL.Float64,
  'supplierId' : IDL.Nat,
  'termsConditions' : IDL.Opt(IDL.Text),
});
export const BillItem = IDL.Record({
  'hsnSac' : IDL.Opt(IDL.Text),
  'discount' : IDL.Float64,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'medicineId' : IDL.Nat,
  'amount' : IDL.Float64,
  'medicineName' : IDL.Text,
});
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerGstin' : IDL.Opt(IDL.Text),
  'balanceAmount' : IDL.Float64,
  'discountAmount' : IDL.Float64,
  'createdAt' : IDL.Int,
  'gstPercent' : IDL.Float64,
  'customerMobile' : IDL.Text,
  'receivedAmount' : IDL.Float64,
  'gstAmount' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'customerId' : IDL.Nat,
  'placeOfSupply' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(BillItem),
  'subtotal' : IDL.Float64,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'expiryDate' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'discount' : IDL.Float64,
  'category' : Category,
  'brand' : IDL.Text,
  'price' : IDL.Float64,
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'gstNo' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'expiringMedicines' : IDL.Vec(Medicine),
  'totalSales' : IDL.Float64,
  'totalMedicines' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'lowStockMedicines' : IDL.Vec(Medicine),
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([CustomerInput], [IDL.Nat], []),
  'addMedicine' : IDL.Func([MedicineInput], [IDL.Nat], []),
  'addSupplier' : IDL.Func([SupplierInput], [IDL.Nat], []),
  'createBill' : IDL.Func(
      [IDL.Nat, IDL.Vec(BillItemInput), IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createBillV2' : IDL.Func([BillInput], [IDL.Nat], []),
  'createSupplierBill' : IDL.Func([SupplierBillInput], [SupplierBill], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
  'deleteSupplier' : IDL.Func([IDL.Nat], [], []),
  'deleteSupplierBill' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getAllSupplierBills' : IDL.Func([], [IDL.Vec(SupplierBill)], ['query']),
  'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getCustomerBills' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
  'getSupplier' : IDL.Func([IDL.Nat], [Supplier], ['query']),
  'getSupplierBill' : IDL.Func([IDL.Nat], [IDL.Opt(SupplierBill)], ['query']),
  'getSupplierBillsBySupplier' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SupplierBill)],
      ['query'],
    ),
  'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'updateCustomer' : IDL.Func([IDL.Nat, CustomerInput], [], []),
  'updateMedicine' : IDL.Func([IDL.Nat, MedicineInput], [], []),
  'updateSupplier' : IDL.Func([IDL.Nat, SupplierInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerInput = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Category = IDL.Variant({
    'Syrup' : IDL.Null,
    'Drops' : IDL.Null,
    'Capsule' : IDL.Null,
    'Injection' : IDL.Null,
    'Tablet' : IDL.Null,
    'Other' : IDL.Null,
    'Cream' : IDL.Null,
  });
  const MedicineInput = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'discount' : IDL.Float64,
    'category' : Category,
    'brand' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SupplierInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gstNo' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const BillItemInput = IDL.Record({
    'hsnSac' : IDL.Opt(IDL.Text),
    'discount' : IDL.Float64,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'medicineId' : IDL.Nat,
    'amount' : IDL.Float64,
    'medicineName' : IDL.Text,
  });
  const BillInput = IDL.Record({
    'customerGstin' : IDL.Opt(IDL.Text),
    'gstPercent' : IDL.Float64,
    'receivedAmount' : IDL.Opt(IDL.Float64),
    'paymentMode' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Nat,
    'placeOfSupply' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(BillItemInput),
  });
  const SupplierBillItem = IDL.Record({
    'sn' : IDL.Nat,
    'hsn' : IDL.Text,
    'mfg' : IDL.Text,
    'mrp' : IDL.Float64,
    'qty' : IDL.Nat,
    'free' : IDL.Nat,
    'pack' : IDL.Text,
    'rate' : IDL.Float64,
    'gstPercent' : IDL.Float64,
    'discPercent' : IDL.Float64,
    'netAmt' : IDL.Float64,
    'expDt' : IDL.Text,
    'itemName' : IDL.Text,
    'batchNo' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const SupplierBillInput = IDL.Record({
    'salesMan' : IDL.Opt(IDL.Text),
    'addLessCnDn' : IDL.Float64,
    'challanNo' : IDL.Opt(IDL.Text),
    'date' : IDL.Int,
    'lrNo' : IDL.Opt(IDL.Text),
    'transport' : IDL.Opt(IDL.Text),
    'invoiceNo' : IDL.Text,
    'cashDiscountTotal' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'freightPktCharge' : IDL.Float64,
    'schemeDiscountTotal' : IDL.Float64,
    'items' : IDL.Vec(SupplierBillItem),
    'cgstAmount' : IDL.Float64,
    'sgstAmount' : IDL.Float64,
    'roundOff' : IDL.Float64,
    'supplierId' : IDL.Nat,
    'termsConditions' : IDL.Opt(IDL.Text),
  });
  const SupplierBill = IDL.Record({
    'id' : IDL.Nat,
    'salesMan' : IDL.Opt(IDL.Text),
    'addLessCnDn' : IDL.Float64,
    'challanNo' : IDL.Opt(IDL.Text),
    'supplierName' : IDL.Text,
    'date' : IDL.Int,
    'lrNo' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'transport' : IDL.Opt(IDL.Text),
    'invoiceNo' : IDL.Text,
    'cashDiscountTotal' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'freightPktCharge' : IDL.Float64,
    'schemeDiscountTotal' : IDL.Float64,
    'items' : IDL.Vec(SupplierBillItem),
    'cgstAmount' : IDL.Float64,
    'sgstAmount' : IDL.Float64,
    'roundOff' : IDL.Float64,
    'supplierId' : IDL.Nat,
    'termsConditions' : IDL.Opt(IDL.Text),
  });
  const BillItem = IDL.Record({
    'hsnSac' : IDL.Opt(IDL.Text),
    'discount' : IDL.Float64,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'medicineId' : IDL.Nat,
    'amount' : IDL.Float64,
    'medicineName' : IDL.Text,
  });
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerGstin' : IDL.Opt(IDL.Text),
    'balanceAmount' : IDL.Float64,
    'discountAmount' : IDL.Float64,
    'createdAt' : IDL.Int,
    'gstPercent' : IDL.Float64,
    'customerMobile' : IDL.Text,
    'receivedAmount' : IDL.Float64,
    'gstAmount' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'customerId' : IDL.Nat,
    'placeOfSupply' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(BillItem),
    'subtotal' : IDL.Float64,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'expiryDate' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'discount' : IDL.Float64,
    'category' : Category,
    'brand' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'gstNo' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'expiringMedicines' : IDL.Vec(Medicine),
    'totalSales' : IDL.Float64,
    'totalMedicines' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'lowStockMedicines' : IDL.Vec(Medicine),
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([CustomerInput], [IDL.Nat], []),
    'addMedicine' : IDL.Func([MedicineInput], [IDL.Nat], []),
    'addSupplier' : IDL.Func([SupplierInput], [IDL.Nat], []),
    'createBill' : IDL.Func(
        [IDL.Nat, IDL.Vec(BillItemInput), IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createBillV2' : IDL.Func([BillInput], [IDL.Nat], []),
    'createSupplierBill' : IDL.Func([SupplierBillInput], [SupplierBill], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
    'deleteSupplier' : IDL.Func([IDL.Nat], [], []),
    'deleteSupplierBill' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getAllSupplierBills' : IDL.Func([], [IDL.Vec(SupplierBill)], ['query']),
    'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getCustomerBills' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
    'getSupplier' : IDL.Func([IDL.Nat], [Supplier], ['query']),
    'getSupplierBill' : IDL.Func([IDL.Nat], [IDL.Opt(SupplierBill)], ['query']),
    'getSupplierBillsBySupplier' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SupplierBill)],
        ['query'],
      ),
    'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'updateCustomer' : IDL.Func([IDL.Nat, CustomerInput], [], []),
    'updateMedicine' : IDL.Func([IDL.Nat, MedicineInput], [], []),
    'updateSupplier' : IDL.Func([IDL.Nat, SupplierInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };