/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'customerName' : string,
  'customerGstin' : [] | [string],
  'balanceAmount' : number,
  'discountAmount' : number,
  'createdAt' : bigint,
  'gstPercent' : number,
  'customerMobile' : string,
  'receivedAmount' : number,
  'gstAmount' : number,
  'invoiceNumber' : string,
  'totalAmount' : number,
  'paymentMode' : string,
  'customerId' : bigint,
  'placeOfSupply' : [] | [string],
  'items' : Array<BillItem>,
  'subtotal' : number,
}
export interface BillInput {
  'customerGstin' : [] | [string],
  'gstPercent' : number,
  'receivedAmount' : [] | [number],
  'paymentMode' : [] | [string],
  'customerId' : bigint,
  'placeOfSupply' : [] | [string],
  'items' : Array<BillItemInput>,
}
export interface BillItem {
  'hsnSac' : [] | [string],
  'discount' : number,
  'quantity' : bigint,
  'price' : number,
  'medicineId' : bigint,
  'amount' : number,
  'medicineName' : string,
}
export interface BillItemInput {
  'hsnSac' : [] | [string],
  'discount' : number,
  'quantity' : bigint,
  'price' : number,
  'medicineId' : bigint,
  'amount' : number,
  'medicineName' : string,
}
export type Category = { 'Syrup' : null } |
  { 'Drops' : null } |
  { 'Capsule' : null } |
  { 'Injection' : null } |
  { 'Tablet' : null } |
  { 'Other' : null } |
  { 'Cream' : null };
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
  'mobile' : string,
}
export interface CustomerInput {
  'name' : string,
  'address' : string,
  'mobile' : string,
}
export interface DashboardStats {
  'expiringMedicines' : Array<Medicine>,
  'totalSales' : number,
  'totalMedicines' : bigint,
  'totalCustomers' : bigint,
  'lowStockMedicines' : Array<Medicine>,
}
export interface Medicine {
  'id' : bigint,
  'stockQuantity' : bigint,
  'expiryDate' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'discount' : number,
  'category' : Category,
  'brand' : string,
  'price' : number,
}
export interface MedicineInput {
  'stockQuantity' : bigint,
  'expiryDate' : bigint,
  'name' : string,
  'discount' : number,
  'category' : Category,
  'brand' : string,
  'price' : number,
}
export interface Supplier {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'gstNo' : string,
  'address' : string,
  'mobile' : string,
}
export interface SupplierBill {
  'id' : bigint,
  'salesMan' : [] | [string],
  'addLessCnDn' : number,
  'challanNo' : [] | [string],
  'supplierName' : string,
  'date' : bigint,
  'lrNo' : [] | [string],
  'createdAt' : bigint,
  'transport' : [] | [string],
  'invoiceNo' : string,
  'cashDiscountTotal' : number,
  'grandTotal' : number,
  'freightPktCharge' : number,
  'schemeDiscountTotal' : number,
  'items' : Array<SupplierBillItem>,
  'cgstAmount' : number,
  'sgstAmount' : number,
  'roundOff' : number,
  'supplierId' : bigint,
  'termsConditions' : [] | [string],
}
export interface SupplierBillInput {
  'salesMan' : [] | [string],
  'addLessCnDn' : number,
  'challanNo' : [] | [string],
  'date' : bigint,
  'lrNo' : [] | [string],
  'transport' : [] | [string],
  'invoiceNo' : string,
  'cashDiscountTotal' : number,
  'grandTotal' : number,
  'freightPktCharge' : number,
  'schemeDiscountTotal' : number,
  'items' : Array<SupplierBillItem>,
  'cgstAmount' : number,
  'sgstAmount' : number,
  'roundOff' : number,
  'supplierId' : bigint,
  'termsConditions' : [] | [string],
}
export interface SupplierBillItem {
  'sn' : bigint,
  'hsn' : string,
  'mfg' : string,
  'mrp' : number,
  'qty' : bigint,
  'free' : bigint,
  'pack' : string,
  'rate' : number,
  'gstPercent' : number,
  'discPercent' : number,
  'netAmt' : number,
  'expDt' : string,
  'itemName' : string,
  'batchNo' : string,
  'amount' : number,
}
export interface SupplierInput {
  'name' : string,
  'email' : string,
  'gstNo' : string,
  'address' : string,
  'mobile' : string,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<[CustomerInput], bigint>,
  'addMedicine' : ActorMethod<[MedicineInput], bigint>,
  'addSupplier' : ActorMethod<[SupplierInput], bigint>,
  'createBill' : ActorMethod<[bigint, Array<BillItemInput>, number], bigint>,
  'createBillV2' : ActorMethod<[BillInput], bigint>,
  'createSupplierBill' : ActorMethod<[SupplierBillInput], SupplierBill>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'deleteSupplier' : ActorMethod<[bigint], undefined>,
  'deleteSupplierBill' : ActorMethod<[bigint], boolean>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getAllSupplierBills' : ActorMethod<[], Array<SupplierBill>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getBill' : ActorMethod<[bigint], Bill>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getCustomerBills' : ActorMethod<[bigint], Array<Bill>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMedicine' : ActorMethod<[bigint], Medicine>,
  'getSupplier' : ActorMethod<[bigint], Supplier>,
  'getSupplierBill' : ActorMethod<[bigint], [] | [SupplierBill]>,
  'getSupplierBillsBySupplier' : ActorMethod<[bigint], Array<SupplierBill>>,
  'searchMedicines' : ActorMethod<[string], Array<Medicine>>,
  'updateCustomer' : ActorMethod<[bigint, CustomerInput], undefined>,
  'updateMedicine' : ActorMethod<[bigint, MedicineInput], undefined>,
  'updateSupplier' : ActorMethod<[bigint, SupplierInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];