/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillItem {
    hsnSac?: string;
    discount: number;
    quantity: bigint;
    price: number;
    medicineId: bigint;
    amount: number;
    medicineName: string;
}
export interface SupplierBillInput {
    salesMan?: string;
    addLessCnDn: number;
    challanNo?: string;
    date: bigint;
    lrNo?: string;
    transport?: string;
    invoiceNo: string;
    cashDiscountTotal: number;
    grandTotal: number;
    freightPktCharge: number;
    schemeDiscountTotal: number;
    items: Array<SupplierBillItem>;
    cgstAmount: number;
    sgstAmount: number;
    roundOff: number;
    supplierId: bigint;
    termsConditions?: string;
}
export interface SupplierBillItem {
    sn: bigint;
    hsn: string;
    mfg: string;
    mrp: number;
    qty: bigint;
    free: bigint;
    pack: string;
    rate: number;
    gstPercent: number;
    discPercent: number;
    netAmt: number;
    expDt: string;
    itemName: string;
    batchNo: string;
    amount: number;
}
export interface MedicineInput {
    stockQuantity: bigint;
    expiryDate: bigint;
    name: string;
    discount: number;
    category: Category;
    brand: string;
    price: number;
}
export interface BillInput {
    customerGstin?: string;
    gstPercent: number;
    receivedAmount?: number;
    paymentMode?: string;
    customerId: bigint;
    placeOfSupply?: string;
    items: Array<BillItemInput>;
}
export interface Customer {
    id: bigint;
    name: string;
    createdAt: bigint;
    address: string;
    mobile: string;
}
export interface DashboardStats {
    expiringMedicines: Array<Medicine>;
    totalSales: number;
    totalMedicines: bigint;
    totalCustomers: bigint;
    lowStockMedicines: Array<Medicine>;
}
export interface SupplierInput {
    name: string;
    email: string;
    gstNo: string;
    address: string;
    mobile: string;
}
export interface CustomerInput {
    name: string;
    address: string;
    mobile: string;
}
export interface BillItemInput {
    hsnSac?: string;
    discount: number;
    quantity: bigint;
    price: number;
    medicineId: bigint;
    amount: number;
    medicineName: string;
}
export interface SupplierBill {
    id: bigint;
    salesMan?: string;
    addLessCnDn: number;
    challanNo?: string;
    supplierName: string;
    date: bigint;
    lrNo?: string;
    createdAt: bigint;
    transport?: string;
    invoiceNo: string;
    cashDiscountTotal: number;
    grandTotal: number;
    freightPktCharge: number;
    schemeDiscountTotal: number;
    items: Array<SupplierBillItem>;
    cgstAmount: number;
    sgstAmount: number;
    roundOff: number;
    supplierId: bigint;
    termsConditions?: string;
}
export interface Medicine {
    id: bigint;
    stockQuantity: bigint;
    expiryDate: bigint;
    name: string;
    createdAt: bigint;
    discount: number;
    category: Category;
    brand: string;
    price: number;
}
export interface Bill {
    id: bigint;
    customerName: string;
    customerGstin?: string;
    balanceAmount: number;
    discountAmount: number;
    createdAt: bigint;
    gstPercent: number;
    customerMobile: string;
    receivedAmount: number;
    gstAmount: number;
    invoiceNumber: string;
    totalAmount: number;
    paymentMode: string;
    customerId: bigint;
    placeOfSupply?: string;
    items: Array<BillItem>;
    subtotal: number;
}
export interface Supplier {
    id: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    gstNo: string;
    address: string;
    mobile: string;
}
export enum Category {
    Syrup = "Syrup",
    Drops = "Drops",
    Capsule = "Capsule",
    Injection = "Injection",
    Tablet = "Tablet",
    Other = "Other",
    Cream = "Cream"
}
export interface backendInterface {
    addCustomer(input: CustomerInput): Promise<bigint>;
    addMedicine(input: MedicineInput): Promise<bigint>;
    addSupplier(input: SupplierInput): Promise<bigint>;
    createBill(customerId: bigint, items: Array<BillItemInput>, gstPercent: number): Promise<bigint>;
    createBillV2(input: BillInput): Promise<bigint>;
    createSupplierBill(input: SupplierBillInput): Promise<SupplierBill>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteMedicine(id: bigint): Promise<void>;
    deleteSupplier(id: bigint): Promise<void>;
    deleteSupplierBill(id: bigint): Promise<boolean>;
    getAllBills(): Promise<Array<Bill>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllMedicines(): Promise<Array<Medicine>>;
    getAllSupplierBills(): Promise<Array<SupplierBill>>;
    getAllSuppliers(): Promise<Array<Supplier>>;
    getBill(id: bigint): Promise<Bill>;
    getCustomer(id: bigint): Promise<Customer>;
    getCustomerBills(customerId: bigint): Promise<Array<Bill>>;
    getDashboardStats(): Promise<DashboardStats>;
    getMedicine(id: bigint): Promise<Medicine>;
    getSupplier(id: bigint): Promise<Supplier>;
    getSupplierBill(id: bigint): Promise<SupplierBill | null>;
    getSupplierBillsBySupplier(supplierId: bigint): Promise<Array<SupplierBill>>;
    searchMedicines(term: string): Promise<Array<Medicine>>;
    updateCustomer(id: bigint, input: CustomerInput): Promise<void>;
    updateMedicine(id: bigint, input: MedicineInput): Promise<void>;
    updateSupplier(id: bigint, input: SupplierInput): Promise<void>;
}
import type { Bill as _Bill, BillInput as _BillInput, BillItem as _BillItem, BillItemInput as _BillItemInput, Category as _Category, DashboardStats as _DashboardStats, Medicine as _Medicine, MedicineInput as _MedicineInput, SupplierBill as _SupplierBill, SupplierBillInput as _SupplierBillInput, SupplierBillItem as _SupplierBillItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: CustomerInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addMedicine(arg0: MedicineInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(to_candid_MedicineInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(to_candid_MedicineInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSupplier(arg0: SupplierInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0);
            return result;
        }
    }
    async createBill(arg0: bigint, arg1: Array<BillItemInput>, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(arg0, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(arg0, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createBillV2(arg0: BillInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBillV2(to_candid_BillInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBillV2(to_candid_BillInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSupplierBill(arg0: SupplierBillInput): Promise<SupplierBill> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupplierBill(to_candid_SupplierBillInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SupplierBill_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupplierBill(to_candid_SupplierBillInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SupplierBill_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async deleteSupplier(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplier(arg0);
            return result;
        }
    }
    async deleteSupplierBill(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplierBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplierBill(arg0);
            return result;
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllMedicines(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSupplierBills(): Promise<Array<SupplierBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupplierBills();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupplierBills();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSuppliers(): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSuppliers();
            return result;
        }
    }
    async getBill(arg0: bigint): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_Bill_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_Bill_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getCustomerBills(arg0: bigint): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerBills(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerBills(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicine(arg0: bigint): Promise<Medicine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicine(arg0);
                return from_candid_Medicine_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicine(arg0);
            return from_candid_Medicine_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplier(arg0: bigint): Promise<Supplier> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return result;
        }
    }
    async getSupplierBill(arg0: bigint): Promise<SupplierBill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierBill(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierBill(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierBillsBySupplier(arg0: bigint): Promise<Array<SupplierBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierBillsBySupplier(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierBillsBySupplier(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchMedicines(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMedicines(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMedicines(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: bigint, arg1: CustomerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateMedicine(arg0: bigint, arg1: MedicineInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, to_candid_MedicineInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, to_candid_MedicineInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSupplier(arg0: bigint, arg1: SupplierInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BillItem_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillItem): BillItem {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Bill_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Medicine_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medicine): Medicine {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SupplierBill_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplierBill): SupplierBill {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierBill]): SupplierBill | null {
    return value.length === 0 ? null : from_candid_SupplierBill_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    salesMan: [] | [string];
    addLessCnDn: number;
    challanNo: [] | [string];
    supplierName: string;
    date: bigint;
    lrNo: [] | [string];
    createdAt: bigint;
    transport: [] | [string];
    invoiceNo: string;
    cashDiscountTotal: number;
    grandTotal: number;
    freightPktCharge: number;
    schemeDiscountTotal: number;
    items: Array<_SupplierBillItem>;
    cgstAmount: number;
    sgstAmount: number;
    roundOff: number;
    supplierId: bigint;
    termsConditions: [] | [string];
}): {
    id: bigint;
    salesMan?: string;
    addLessCnDn: number;
    challanNo?: string;
    supplierName: string;
    date: bigint;
    lrNo?: string;
    createdAt: bigint;
    transport?: string;
    invoiceNo: string;
    cashDiscountTotal: number;
    grandTotal: number;
    freightPktCharge: number;
    schemeDiscountTotal: number;
    items: Array<SupplierBillItem>;
    cgstAmount: number;
    sgstAmount: number;
    roundOff: number;
    supplierId: bigint;
    termsConditions?: string;
} {
    return {
        id: value.id,
        salesMan: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.salesMan)),
        addLessCnDn: value.addLessCnDn,
        challanNo: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.challanNo)),
        supplierName: value.supplierName,
        date: value.date,
        lrNo: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lrNo)),
        createdAt: value.createdAt,
        transport: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.transport)),
        invoiceNo: value.invoiceNo,
        cashDiscountTotal: value.cashDiscountTotal,
        grandTotal: value.grandTotal,
        freightPktCharge: value.freightPktCharge,
        schemeDiscountTotal: value.schemeDiscountTotal,
        items: value.items,
        cgstAmount: value.cgstAmount,
        sgstAmount: value.sgstAmount,
        roundOff: value.roundOff,
        supplierId: value.supplierId,
        termsConditions: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.termsConditions))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    customerGstin: [] | [string];
    balanceAmount: number;
    discountAmount: number;
    createdAt: bigint;
    gstPercent: number;
    customerMobile: string;
    receivedAmount: number;
    gstAmount: number;
    invoiceNumber: string;
    totalAmount: number;
    paymentMode: string;
    customerId: bigint;
    placeOfSupply: [] | [string];
    items: Array<_BillItem>;
    subtotal: number;
}): {
    id: bigint;
    customerName: string;
    customerGstin?: string;
    balanceAmount: number;
    discountAmount: number;
    createdAt: bigint;
    gstPercent: number;
    customerMobile: string;
    receivedAmount: number;
    gstAmount: number;
    invoiceNumber: string;
    totalAmount: number;
    paymentMode: string;
    customerId: bigint;
    placeOfSupply?: string;
    items: Array<BillItem>;
    subtotal: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        customerGstin: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.customerGstin)),
        balanceAmount: value.balanceAmount,
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        customerMobile: value.customerMobile,
        receivedAmount: value.receivedAmount,
        gstAmount: value.gstAmount,
        invoiceNumber: value.invoiceNumber,
        totalAmount: value.totalAmount,
        paymentMode: value.paymentMode,
        customerId: value.customerId,
        placeOfSupply: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.placeOfSupply)),
        items: from_candid_vec_n18(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hsnSac: [] | [string];
    discount: number;
    quantity: bigint;
    price: number;
    medicineId: bigint;
    amount: number;
    medicineName: string;
}): {
    hsnSac?: string;
    discount: number;
    quantity: bigint;
    price: number;
    medicineId: bigint;
    amount: number;
    medicineName: string;
} {
    return {
        hsnSac: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.hsnSac)),
        discount: value.discount,
        quantity: value.quantity,
        price: value.price,
        medicineId: value.medicineId,
        amount: value.amount,
        medicineName: value.medicineName
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockQuantity: bigint;
    expiryDate: bigint;
    name: string;
    createdAt: bigint;
    discount: number;
    category: _Category;
    brand: string;
    price: number;
}): {
    id: bigint;
    stockQuantity: bigint;
    expiryDate: bigint;
    name: string;
    createdAt: bigint;
    discount: number;
    category: Category;
    brand: string;
    price: number;
} {
    return {
        id: value.id,
        stockQuantity: value.stockQuantity,
        expiryDate: value.expiryDate,
        name: value.name,
        createdAt: value.createdAt,
        discount: value.discount,
        category: from_candid_Category_n24(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: value.price
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiringMedicines: Array<_Medicine>;
    totalSales: number;
    totalMedicines: bigint;
    totalCustomers: bigint;
    lowStockMedicines: Array<_Medicine>;
}): {
    expiringMedicines: Array<Medicine>;
    totalSales: number;
    totalMedicines: bigint;
    totalCustomers: bigint;
    lowStockMedicines: Array<Medicine>;
} {
    return {
        expiringMedicines: from_candid_vec_n21(_uploadFile, _downloadFile, value.expiringMedicines),
        totalSales: value.totalSales,
        totalMedicines: value.totalMedicines,
        totalCustomers: value.totalCustomers,
        lowStockMedicines: from_candid_vec_n21(_uploadFile, _downloadFile, value.lowStockMedicines)
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Syrup: null;
} | {
    Drops: null;
} | {
    Capsule: null;
} | {
    Injection: null;
} | {
    Tablet: null;
} | {
    Other: null;
} | {
    Cream: null;
}): Category {
    return "Syrup" in value ? Category.Syrup : "Drops" in value ? Category.Drops : "Capsule" in value ? Category.Capsule : "Injection" in value ? Category.Injection : "Tablet" in value ? Category.Tablet : "Other" in value ? Category.Other : "Cream" in value ? Category.Cream : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillItem>): Array<BillItem> {
    return value.map((x)=>from_candid_BillItem_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medicine>): Array<Medicine> {
    return value.map((x)=>from_candid_Medicine_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupplierBill>): Array<SupplierBill> {
    return value.map((x)=>from_candid_SupplierBill_n12(_uploadFile, _downloadFile, x));
}
function to_candid_BillInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillInput): _BillInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BillItemInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillItemInput): _BillItemInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MedicineInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicineInput): _MedicineInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SupplierBillInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierBillInput): _SupplierBillInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salesMan?: string;
    addLessCnDn: number;
    challanNo?: string;
    date: bigint;
    lrNo?: string;
    transport?: string;
    invoiceNo: string;
    cashDiscountTotal: number;
    grandTotal: number;
    freightPktCharge: number;
    schemeDiscountTotal: number;
    items: Array<SupplierBillItem>;
    cgstAmount: number;
    sgstAmount: number;
    roundOff: number;
    supplierId: bigint;
    termsConditions?: string;
}): {
    salesMan: [] | [string];
    addLessCnDn: number;
    challanNo: [] | [string];
    date: bigint;
    lrNo: [] | [string];
    transport: [] | [string];
    invoiceNo: string;
    cashDiscountTotal: number;
    grandTotal: number;
    freightPktCharge: number;
    schemeDiscountTotal: number;
    items: Array<_SupplierBillItem>;
    cgstAmount: number;
    sgstAmount: number;
    roundOff: number;
    supplierId: bigint;
    termsConditions: [] | [string];
} {
    return {
        salesMan: value.salesMan ? candid_some(value.salesMan) : candid_none(),
        addLessCnDn: value.addLessCnDn,
        challanNo: value.challanNo ? candid_some(value.challanNo) : candid_none(),
        date: value.date,
        lrNo: value.lrNo ? candid_some(value.lrNo) : candid_none(),
        transport: value.transport ? candid_some(value.transport) : candid_none(),
        invoiceNo: value.invoiceNo,
        cashDiscountTotal: value.cashDiscountTotal,
        grandTotal: value.grandTotal,
        freightPktCharge: value.freightPktCharge,
        schemeDiscountTotal: value.schemeDiscountTotal,
        items: value.items,
        cgstAmount: value.cgstAmount,
        sgstAmount: value.sgstAmount,
        roundOff: value.roundOff,
        supplierId: value.supplierId,
        termsConditions: value.termsConditions ? candid_some(value.termsConditions) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockQuantity: bigint;
    expiryDate: bigint;
    name: string;
    discount: number;
    category: Category;
    brand: string;
    price: number;
}): {
    stockQuantity: bigint;
    expiryDate: bigint;
    name: string;
    discount: number;
    category: _Category;
    brand: string;
    price: number;
} {
    return {
        stockQuantity: value.stockQuantity,
        expiryDate: value.expiryDate,
        name: value.name,
        discount: value.discount,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: value.price
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hsnSac?: string;
    discount: number;
    quantity: bigint;
    price: number;
    medicineId: bigint;
    amount: number;
    medicineName: string;
}): {
    hsnSac: [] | [string];
    discount: number;
    quantity: bigint;
    price: number;
    medicineId: bigint;
    amount: number;
    medicineName: string;
} {
    return {
        hsnSac: value.hsnSac ? candid_some(value.hsnSac) : candid_none(),
        discount: value.discount,
        quantity: value.quantity,
        price: value.price,
        medicineId: value.medicineId,
        amount: value.amount,
        medicineName: value.medicineName
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerGstin?: string;
    gstPercent: number;
    receivedAmount?: number;
    paymentMode?: string;
    customerId: bigint;
    placeOfSupply?: string;
    items: Array<BillItemInput>;
}): {
    customerGstin: [] | [string];
    gstPercent: number;
    receivedAmount: [] | [number];
    paymentMode: [] | [string];
    customerId: bigint;
    placeOfSupply: [] | [string];
    items: Array<_BillItemInput>;
} {
    return {
        customerGstin: value.customerGstin ? candid_some(value.customerGstin) : candid_none(),
        gstPercent: value.gstPercent,
        receivedAmount: value.receivedAmount ? candid_some(value.receivedAmount) : candid_none(),
        paymentMode: value.paymentMode ? candid_some(value.paymentMode) : candid_none(),
        customerId: value.customerId,
        placeOfSupply: value.placeOfSupply ? candid_some(value.placeOfSupply) : candid_none(),
        items: to_candid_vec_n5(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Syrup: null;
} | {
    Drops: null;
} | {
    Capsule: null;
} | {
    Injection: null;
} | {
    Tablet: null;
} | {
    Other: null;
} | {
    Cream: null;
} {
    return value == Category.Syrup ? {
        Syrup: null
    } : value == Category.Drops ? {
        Drops: null
    } : value == Category.Capsule ? {
        Capsule: null
    } : value == Category.Injection ? {
        Injection: null
    } : value == Category.Tablet ? {
        Tablet: null
    } : value == Category.Other ? {
        Other: null
    } : value == Category.Cream ? {
        Cream: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BillItemInput>): Array<_BillItemInput> {
    return value.map((x)=>to_candid_BillItemInput_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
